spring.application.name=backend
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile